### ISSUE TITLE
Documentation missing typescript instructions

### ISSUE THREAD

**Issue by jvasile** [PermanentOrg/ep_permanent_exporter#1]
I had to install typescript or I received complaints about missing tsc.  We should probably tell the user to install that before building.  I haven't used typescript with npm before, but the solution appears to be `npm install -g typescript` or perhaps `apt-get install node-typescript`.  @jasonaowen would you document the correct answer(s) for users like me who want to install this thing but have forgotten everything they ever knew about npm?

**Comment by jasonaowen** [comment]
You should not need to install TypeScript globally, which is what the two commands you listed do. We depend on the specific version of TypeScript we need in [our `package.json`](https://github.com/PermanentOrg/ep_permanent_exporter/blob/main/package.json#L26-L39), so running `npm install` should be enough. Are you able to build successfully after running `npm install`?

**Comment by jvasile** [comment]
npm install appears to have worked well enough, so I'm closing this for now.  Massive thanks!
