### ISSUE TITLE
npm run build doesn't work

### ISSUE THREAD

**Issue by jvasile** [PermanentOrg/ep_permanent_exporter#2]
The documentation says to run `npm run build`.  Here's what happens when I do:

    $ npm run build > t
    $ cat t

    > ep_permanent_exporter@0.0.1 build
    > tsc

    src/client/document-ready.ts(1,25): error TS2307: Cannot find module 'jquery' or its corresponding type declarations.
    src/client/document-ready.ts(11,3): error TS2581: Cannot find name '$'. Do you need to install type definitions for jQuery? Try `npm i --save-dev @types/jquery`.
    src/client/document-ready.ts(17,5): error TS2581: Cannot find name '$'. Do you need to install type definitions for jQuery? Try `npm i --save-dev @types/jquery`.
    src/client/document-ready.ts(22,17): error TS2581: Cannot find name '$'. Do you need to install type definitions for jQuery? Try `npm i --save-dev @types/jquery`.
    src/client/document-ready.ts(23,17): error TS2581: Cannot find name '$'. Do you need to install type definitions for jQuery? Try `npm i --save-dev @types/jquery`.
    src/server/express-create-server.ts(8,8): error TS2307: Cannot find module 'express' or its corresponding type declarations.
    src/server/express-create-server.ts(9,24): error TS2307: Cannot find module 'body-parser' or its corresponding type declarations.
    src/server/pad-update.ts(3,26): error TS2307: Cannot find module 'lodash' or its corresponding type declarations.
    tsconfig.json(2,14): error TS6053: File '@tsconfig/node10/tsconfig.json' not found.

So I tried to install jquery types as per the error message:

    $ npm i --save-dev @types/jquery
    npm WARN ERESOLVE overriding peer dependency
    npm WARN Found: ep_etherpad-lite@undefined
    npm WARN node_modules/ep_etherpad-lite
    npm WARN   peer ep_etherpad-lite@"^1.8.7" from the root project
    npm WARN 
    npm WARN Could not resolve dependency:
    npm WARN peer ep_etherpad-lite@"^1.8.7" from the root project
    npm ERR! code ENOVERSIONS
    npm ERR! No versions available for ep_etherpad-lite

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/james/.npm/_logs/2021-04-03T22_34_15_038Z-debug.log

No luck.  Obviously I'm doing something wrong.  If I need to do things before `npm run build` we should document them.

**Comment by jasonaowen** [comment]
The documentation definitely needs some work! In both this case and in #1, it sounds like you were having some trouble with dependencies. We do already depend on `@types/jquery`, so you should not need to add that dependency; instead, you should be able to `npm install` as a first step after checking out the repository locally. I believe there will emit some warnings, but it should exit successfully. If it exits unsuccessfully, can you please attach the output?

After installing the dependencies, please try `npm run build` again and let me know if that works for you!

**Comment by jvasile** [comment]
Ah, thank you!  I thought build contained an implicit "install as needed".  Starting with npm install got me further:

    $ npm install
    npm WARN ep_permanent_exporter@0.0.1 requires a peer of ep_etherpad-lite@^1.8.7 but none is installed. You must install peer dependencies yourself.
    npm WARN ep_permanent_exporter@0.0.1 requires a peer of express@^4.17.1 but none is installed. You must install peer dependencies yourself.
    npm WARN ep_permanent_exporter@0.0.1 No repository field.

And then `npm run build` got me to here:

     > ep_permanent_exporter@0.0.1 build /home/etherpad/src/ep_permanent_exporter
     > tsc
     
I am not clear on whether that succeeded, and if so, what do I now take and stick into Etherpad somewhere?

**Comment by jasonaowen** [comment]
That looks like success! Now you should be able to install the plugin by going into the Etherpad root and running `npm install /path/to/plugin`.

**Comment by jasonaowen** [comment]
After further pairing with @jvasile, it seems we were running into some issues with a change to how plugins are managed. I opened a new issue for that; in the meantime, I think this issue is resolved with commit 620b3c8a6bd9f6c8d8f1d29747230f54e098a9e4.
